<?php
/**
 * Demo Data for CrossConnect MY
 * Static data for testing without database
 */

// Demo States
function getDemoStates()
{
    return [
        ['id' => 1, 'name' => 'Johor', 'slug' => 'johor', 'region' => 'peninsular'],
        ['id' => 2, 'name' => 'Kedah', 'slug' => 'kedah', 'region' => 'peninsular'],
        ['id' => 3, 'name' => 'Kelantan', 'slug' => 'kelantan', 'region' => 'peninsular'],
        ['id' => 4, 'name' => 'Melaka', 'slug' => 'melaka', 'region' => 'peninsular'],
        ['id' => 5, 'name' => 'Negeri Sembilan', 'slug' => 'negeri-sembilan', 'region' => 'peninsular'],
        ['id' => 6, 'name' => 'Pahang', 'slug' => 'pahang', 'region' => 'peninsular'],
        ['id' => 7, 'name' => 'Penang', 'slug' => 'penang', 'region' => 'peninsular'],
        ['id' => 8, 'name' => 'Perak', 'slug' => 'perak', 'region' => 'peninsular'],
        ['id' => 9, 'name' => 'Perlis', 'slug' => 'perlis', 'region' => 'peninsular'],
        ['id' => 10, 'name' => 'Sabah', 'slug' => 'sabah', 'region' => 'east_malaysia'],
        ['id' => 11, 'name' => 'Sarawak', 'slug' => 'sarawak', 'region' => 'east_malaysia'],
        ['id' => 12, 'name' => 'Selangor', 'slug' => 'selangor', 'region' => 'peninsular'],
        ['id' => 13, 'name' => 'Terengganu', 'slug' => 'terengganu', 'region' => 'peninsular'],
        ['id' => 14, 'name' => 'Kuala Lumpur', 'slug' => 'kuala-lumpur', 'region' => 'federal_territory'],
        ['id' => 15, 'name' => 'Labuan', 'slug' => 'labuan', 'region' => 'federal_territory'],
        ['id' => 16, 'name' => 'Putrajaya', 'slug' => 'putrajaya', 'region' => 'federal_territory'],
    ];
}

// Demo Churches
function getDemoChurches()
{
    return [
        [
            'id' => 1,
            'name' => 'Grace Assembly Kuala Lumpur',
            'slug' => 'grace-assembly-kuala-lumpur',
            'city' => 'Mont Kiara',
            'address' => '10, Jalan Kiara 5, Mont Kiara, 50480 Kuala Lumpur',
            'phone' => '03-1234 5678',
            'email' => 'info@gracekl.org',
            'website' => 'https://gracekl.org',
            'facebook' => 'graceassemblykl',
            'instagram' => 'gracekl_official',
            'youtube' => 'graceassemblykl',
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?w=400&h=250&fit=crop',
            'description' => 'A vibrant Pentecostal church in the heart of Mont Kiara, serving the community with passion and love.',
            'is_featured' => 1,
            'latitude' => 3.1715,
            'longitude' => 101.6536,
            'state_name' => 'Kuala Lumpur',
            'state_slug' => 'kuala-lumpur',
            'denomination_name' => 'Pentecostal',
            'denomination_slug' => 'pentecostal'
        ],
        [
            'id' => 2,
            'name' => 'St. Andrew\'s Presbyterian Church Penang',
            'slug' => 'st-andrews-presbyterian-penang',
            'city' => 'George Town',
            'address' => '2, Lebuh Gereja, George Town, 10200 Penang',
            'phone' => '04-261 7243',
            'email' => 'office@standrewspenang.org.my',
            'website' => 'https://standrewspenang.org.my',
            'facebook' => 'standrewspenang',
            'instagram' => null,
            'youtube' => null,
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1519982710790-a858f3bc4e03?w=400&h=250&fit=crop',
            'description' => 'Historic Presbyterian church established in 1818, the oldest Presbyterian church in Southeast Asia.',
            'is_featured' => 0,
            'latitude' => 5.4145,
            'longitude' => 100.3354,
            'state_name' => 'Penang',
            'state_slug' => 'penang',
            'denomination_name' => 'Presbyterian',
            'denomination_slug' => 'presbyterian'
        ],
        [
            'id' => 3,
            'name' => 'Hope City Church Kota Kinabalu',
            'slug' => 'hope-city-kk',
            'city' => 'Kota Kinabalu',
            'address' => 'Lot 3, Block B, Lorong Pokok Kayu Manis 2, 88300 Kota Kinabalu',
            'phone' => '088-232 888',
            'email' => 'hello@hopecity.my',
            'website' => 'https://hopecity.my',
            'facebook' => 'hopecitykk',
            'instagram' => 'hopecitykk',
            'youtube' => 'hopecitykk',
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=400&h=250&fit=crop',
            'description' => 'A non-denominational church passionate about reaching the community in Sabah.',
            'is_featured' => 0,
            'latitude' => 5.9804,
            'longitude' => 116.0735,
            'state_name' => 'Sabah',
            'state_slug' => 'sabah',
            'denomination_name' => 'Non-Denominational',
            'denomination_slug' => 'non-denominational'
        ],
        [
            'id' => 4,
            'name' => 'Wesley Methodist Church Melaka',
            'slug' => 'wesley-methodist-melaka',
            'city' => 'Melaka City',
            'address' => '188, Jalan Tengkera, 75200 Melaka',
            'phone' => '06-282 5818',
            'email' => 'wesleymelaka@gmail.com',
            'website' => 'https://wesleymelaka.org.my',
            'facebook' => 'wesleymelaka',
            'instagram' => null,
            'youtube' => null,
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=400&h=250&fit=crop',
            'description' => 'Historic Methodist church in the heart of Melaka.',
            'is_featured' => 0,
            'latitude' => 2.1896,
            'longitude' => 102.2501,
            'state_name' => 'Melaka',
            'state_slug' => 'melaka',
            'denomination_name' => 'Methodist',
            'denomination_slug' => 'methodist'
        ],
        [
            'id' => 5,
            'name' => 'Calvary Church Damansara',
            'slug' => 'calvary-church-damansara',
            'city' => 'Damansara Heights',
            'address' => '2, Jalan Damansara Endah, Damansara Heights, 50490 Kuala Lumpur',
            'phone' => '03-2093 7722',
            'email' => 'info@calvarychurch.my',
            'website' => 'https://calvarychurch.my',
            'facebook' => 'calvarychurchmy',
            'instagram' => 'calvarychurchmy',
            'youtube' => 'calvarychurchmy',
            'twitter' => 'calvarychurchmy',
            'image_url' => 'https://images.unsplash.com/photo-1510936111840-65e151ad71bb?w=400&h=250&fit=crop',
            'description' => 'Assemblies of God church with a heart for missions and discipleship.',
            'is_featured' => 1,
            'latitude' => 3.1526,
            'longitude' => 101.6647,
            'state_name' => 'Selangor',
            'state_slug' => 'selangor',
            'denomination_name' => 'Assemblies of God',
            'denomination_slug' => 'assemblies-of-god'
        ],
        [
            'id' => 6,
            'name' => 'Sacred Heart Catholic Cathedral JB',
            'slug' => 'sacred-heart-cathedral-jb',
            'city' => 'Johor Bahru',
            'address' => 'Jalan Gereja, Bandar Johor Bahru, 80000 Johor Bahru',
            'phone' => '07-224 2052',
            'email' => 'sacredheart@catholicjb.org',
            'website' => 'https://sacredheartjb.org',
            'facebook' => 'sacredheartjb',
            'instagram' => null,
            'youtube' => null,
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1520500807606-4ac9ae633574?w=400&h=250&fit=crop',
            'description' => 'The Cathedral of the Catholic Diocese of Malacca-Johore, a beautiful heritage building.',
            'is_featured' => 0,
            'latitude' => 1.4655,
            'longitude' => 103.7578,
            'state_name' => 'Johor',
            'state_slug' => 'johor',
            'denomination_name' => 'Catholic',
            'denomination_slug' => 'catholic'
        ],
        [
            'id' => 7,
            'name' => 'SIBKL Full Gospel Assembly',
            'slug' => 'sibkl-full-gospel',
            'city' => 'Petaling Jaya',
            'address' => 'Lot 5, Jalan 13/1, Seksyen 13, 46200 Petaling Jaya',
            'phone' => '03-7957 2277',
            'email' => 'info@sibkl.org.my',
            'website' => 'https://sibkl.org.my',
            'facebook' => 'sibkl',
            'instagram' => 'sibkl',
            'youtube' => 'sibkl',
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1545296664-39db56ad95bd?w=400&h=250&fit=crop',
            'description' => 'One of the largest Full Gospel churches in Malaysia with a strong missions focus.',
            'is_featured' => 1,
            'latitude' => 3.1082,
            'longitude' => 101.6389,
            'state_name' => 'Selangor',
            'state_slug' => 'selangor',
            'denomination_name' => 'Full Gospel',
            'denomination_slug' => 'full-gospel'
        ],
        [
            'id' => 8,
            'name' => 'St. Joseph\'s Cathedral Kuching',
            'slug' => 'st-josephs-cathedral-kuching',
            'city' => 'Kuching',
            'address' => 'Jalan Tun Abang Haji Openg, 93000 Kuching',
            'phone' => '082-242 467',
            'email' => 'cathedral@stjosephskuching.org',
            'website' => 'https://stjosephskuching.org',
            'facebook' => 'stjosephskuching',
            'instagram' => null,
            'youtube' => null,
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1505455184862-554165e5f6ba?w=400&h=250&fit=crop',
            'description' => 'The mother church of the Catholic Archdiocese of Kuching.',
            'is_featured' => 0,
            'latitude' => 1.5535,
            'longitude' => 110.3593,
            'state_name' => 'Sarawak',
            'state_slug' => 'sarawak',
            'denomination_name' => 'Catholic',
            'denomination_slug' => 'catholic'
        ],
        [
            'id' => 9,
            'name' => 'St. Michael\'s Anglican Church Ipoh',
            'slug' => 'st-michaels-ipoh',
            'city' => 'Ipoh',
            'address' => 'Jalan Raja Dihilir, 30350 Ipoh',
            'phone' => '05-254 2186',
            'email' => 'stmichael@anglicanchurch.my',
            'website' => 'https://stmichaelsipoh.org',
            'facebook' => 'stmichaelsipoh',
            'instagram' => null,
            'youtube' => null,
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=400&h=250&fit=crop',
            'description' => 'Historic Anglican church in Ipoh, established in 1912.',
            'is_featured' => 0,
            'latitude' => 4.5975,
            'longitude' => 101.0901,
            'state_name' => 'Perak',
            'state_slug' => 'perak',
            'denomination_name' => 'Anglican',
            'denomination_slug' => 'anglican'
        ],
        [
            'id' => 10,
            'name' => 'DUMC Damansara Utama Methodist Church',
            'slug' => 'dumc-damansara',
            'city' => 'Damansara Utama',
            'address' => '23, Jalan SS 21/39, Damansara Utama, 47400 Petaling Jaya',
            'phone' => '03-7728 6000',
            'email' => 'info@dumc.my',
            'website' => 'https://dumc.my',
            'facebook' => 'dumcmalaysia',
            'instagram' => 'dumcmalaysia',
            'youtube' => 'dumcmalaysia',
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=400&h=250&fit=crop',
            'description' => 'One of the largest Methodist churches in Southeast Asia, known for community service and vibrant worship.',
            'is_featured' => 1,
            'latitude' => 3.1251,
            'longitude' => 101.6184,
            'state_name' => 'Kuala Lumpur',
            'state_slug' => 'kuala-lumpur',
            'denomination_name' => 'Methodist',
            'denomination_slug' => 'methodist'
        ],
        [
            'id' => 11,
            'name' => 'City Harvest Church Johor Bahru',
            'slug' => 'city-harvest-jb',
            'city' => 'Johor Bahru',
            'address' => '88, Jalan Ibrahim Sultan, Stulang Laut, 80300 Johor Bahru',
            'phone' => '07-222 8888',
            'email' => 'jb@cityharvest.com.my',
            'website' => 'https://cityharvest.com.my',
            'facebook' => 'cityharvestjb',
            'instagram' => 'cityharvestjb',
            'youtube' => 'cityharvestjb',
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1574169208507-84376144065b?w=400&h=250&fit=crop',
            'description' => 'Contemporary Pentecostal church with dynamic worship and community programs.',
            'is_featured' => 0,
            'latitude' => 1.4684,
            'longitude' => 103.7614,
            'state_name' => 'Johor',
            'state_slug' => 'johor',
            'denomination_name' => 'Pentecostal',
            'denomination_slug' => 'pentecostal'
        ],
        [
            'id' => 12,
            'name' => 'Wesley Methodist Church Penang',
            'slug' => 'wesley-methodist-penang',
            'city' => 'Tanjung Bungah',
            'address' => '37, Lorong Lembah Permai 1, 11200 Tanjung Bungah, Penang',
            'phone' => '04-890 3377',
            'email' => 'wesleypenang@methodist.org.my',
            'website' => 'https://wesleypenang.org.my',
            'facebook' => 'wesleymcpenang',
            'instagram' => 'wesleymcpenang',
            'youtube' => null,
            'twitter' => null,
            'image_url' => 'https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=400&h=250&fit=crop',
            'description' => 'A Methodist church committed to making disciples of Jesus Christ.',
            'is_featured' => 0,
            'latitude' => 5.4631,
            'longitude' => 100.2867,
            'state_name' => 'Penang',
            'state_slug' => 'penang',
            'denomination_name' => 'Methodist',
            'denomination_slug' => 'methodist'
        ]
    ];
}

// Demo Events
function getDemoEvents()
{
    return [
        [
            'id' => 1,
            'name' => 'New Year Prayer & Praise Night 2025',
            'slug' => 'new-year-prayer-praise-2025',
            'poster_url' => 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=600&h=400&fit=crop',
            'event_date' => '2025-01-01',
            'event_end_date' => null,
            'event_time' => '10:00 PM - 1:00 AM',
            'description' => "Join us as we usher in the New Year with prayer, worship, and thanksgiving. A powerful night of intercession and praise as we dedicate 2025 to the Lord.\n\nSpecial guest worship leaders from across Malaysia will be leading us in an atmosphere of breakthrough and celebration.",
            'organizer' => 'Grace Assembly KL',
            'venue' => 'Grace Assembly Hall',
            'venue_address' => '10, Jalan Kiara 5, Mont Kiara, 50480 Kuala Lumpur',
            'state_name' => 'Kuala Lumpur',
            'state_slug' => 'kuala-lumpur',
            'website_url' => 'https://gracekl.org/events',
            'registration_url' => null,
            'whatsapp' => '60123456789',
            'phone' => '03-1234 5678',
            'email' => 'events@gracekl.org',
            'is_featured' => 1,
            'status' => 'upcoming'
        ],
        [
            'id' => 2,
            'name' => 'Youth Ignite Conference 2025',
            'slug' => 'youth-ignite-conference-2025',
            'poster_url' => 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=600&h=400&fit=crop',
            'event_date' => '2025-01-10',
            'event_end_date' => '2025-01-12',
            'event_time' => '9:00 AM - 5:00 PM',
            'description' => "A 3-day conference designed to ignite the fire of God in the hearts of young people. Featuring dynamic speakers, powerful worship, and life-changing workshops.\n\n**Speakers:**\n- Pastor John Lim (DUMC)\n- Rev. Sarah Tan (SIBKL)\n- Ps. David Wong (Calvary Church)\n\nFor ages 13-25. Early bird registration ends Dec 31.",
            'organizer' => 'Malaysian Youth Network',
            'venue' => 'DUMC Main Sanctuary',
            'venue_address' => '23, Jalan SS 21/39, Damansara Utama, 47400 PJ',
            'state_name' => 'Selangor',
            'state_slug' => 'selangor',
            'website_url' => 'https://youthignite.my',
            'registration_url' => 'https://youthignite.my/register',
            'whatsapp' => '60198765432',
            'phone' => '03-7728 6000',
            'email' => 'info@youthignite.my',
            'is_featured' => 1,
            'status' => 'upcoming'
        ],
        [
            'id' => 3,
            'name' => 'Marriage Enrichment Retreat',
            'slug' => 'marriage-enrichment-retreat-jan-2025',
            'poster_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=400&fit=crop',
            'event_date' => '2025-01-17',
            'event_end_date' => '2025-01-19',
            'event_time' => 'Friday 6PM - Sunday 2PM',
            'description' => "Strengthen your marriage at this intimate weekend retreat. Learn practical tools for better communication, conflict resolution, and deepening your spiritual connection as a couple.\n\nIncludes accommodation, meals, and all sessions. Limited to 20 couples.",
            'organizer' => 'FCBC Marriage Ministry',
            'venue' => 'Awana Genting Highlands',
            'venue_address' => 'Genting Highlands Resort, 69000 Pahang',
            'state_name' => 'Pahang',
            'state_slug' => 'pahang',
            'website_url' => null,
            'registration_url' => 'https://fcbc.org.my/marriage-retreat',
            'whatsapp' => '60177654321',
            'phone' => '03-5631 5155',
            'email' => 'marriage@fcbc.org.my',
            'is_featured' => 0,
            'status' => 'upcoming'
        ],
        [
            'id' => 4,
            'name' => 'Worship Leaders Workshop',
            'slug' => 'worship-leaders-workshop-2025',
            'poster_url' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&h=400&fit=crop',
            'event_date' => '2025-01-25',
            'event_end_date' => null,
            'event_time' => '9:00 AM - 4:00 PM',
            'description' => "A comprehensive workshop for worship leaders and musicians. Learn about leading worship with excellence, team dynamics, sound engineering basics, and cultivating a heart of worship.\n\nOpen to worship team members from all churches. Lunch provided.",
            'organizer' => 'SIBKL Worship Academy',
            'venue' => 'SIBKL Auditorium',
            'venue_address' => 'Lot 5, Jalan 13/1, Seksyen 13, 46200 PJ',
            'state_name' => 'Selangor',
            'state_slug' => 'selangor',
            'website_url' => 'https://sibkl.org.my/worship',
            'registration_url' => 'https://forms.gle/worship2025',
            'whatsapp' => '60129876543',
            'phone' => '03-7957 2277',
            'email' => 'worship@sibkl.org.my',
            'is_featured' => 0,
            'status' => 'upcoming'
        ],
        [
            'id' => 5,
            'name' => 'Chinese New Year Evangelism Training',
            'slug' => 'cny-evangelism-training-2025',
            'poster_url' => 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600&h=400&fit=crop',
            'event_date' => '2025-01-18',
            'event_end_date' => null,
            'event_time' => '2:00 PM - 5:00 PM',
            'description' => "Prepare to share the Good News during the CNY season! Learn culturally-sensitive approaches to sharing your faith with family and friends during reunion gatherings.\n\nIncludes evangelism materials and CNY tract packs.",
            'organizer' => 'Wesley Methodist Penang',
            'venue' => 'Wesley Hall',
            'venue_address' => '37, Lorong Lembah Permai 1, 11200 Tanjung Bungah',
            'state_name' => 'Penang',
            'state_slug' => 'penang',
            'website_url' => null,
            'registration_url' => null,
            'whatsapp' => '60164567890',
            'phone' => '04-890 3377',
            'email' => 'outreach@wesleypenang.org.my',
            'is_featured' => 0,
            'status' => 'upcoming'
        ],
        [
            'id' => 6,
            'name' => 'Prayer Mountain Retreat',
            'slug' => 'prayer-mountain-retreat-jan-2025',
            'poster_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop',
            'event_date' => '2025-01-24',
            'event_end_date' => '2025-01-26',
            'event_time' => 'Friday 4PM - Sunday 12PM',
            'description' => "Escape the busyness of life and encounter God at this prayer retreat in the serene Cameron Highlands. Three days of soaking prayer, fasting, and seeking the Lord together.\n\nTransport from KL available. All meals (breaking fast) included.",
            'organizer' => 'Hope City Church KK',
            'venue' => 'Cameron Highlands Prayer Centre',
            'venue_address' => 'Lot 88, Tanah Rata, 39000 Cameron Highlands',
            'state_name' => 'Pahang',
            'state_slug' => 'pahang',
            'website_url' => 'https://hopecity.my/retreats',
            'registration_url' => 'https://hopecity.my/retreats/register',
            'whatsapp' => '60188887777',
            'phone' => '088-232 888',
            'email' => 'retreats@hopecity.my',
            'is_featured' => 1,
            'status' => 'upcoming'
        ]
    ];
}
